# Basic
title: D-lyw
subtitle: I think, therefore I am.
welcome_message: I'm on the way ...
description: Record、Share and Exchange Knowlegde & Thinking
creator: <a href="https://dlyw.top">D-lyw</a>

url: "https://dlyw.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
#cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
      - {title: Gitbook, description: My Gitbook, url: 'https://liuyuanwang4321.gitbook.io/workspace/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: https-d-lyw-github-io
    # duoshuo: 
    
# Social
social:
        # weibo: onevcat
    github: D-lyw
    #   twitter: onevcat
    mail: liuyuanwang4321@gmail.com
    medium: my medium

# Google Analytics
ga:
    id: UA-146221372-1
    host: https://dlyw.top
